language: node_js

node_js:
  - 14

rvm:
  - 2.7

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash

before_script:
  # install dependencies
  # travis runs `yarn install` when yarn.lock exists

  # install ruby dependencies
  - gem install bundler
  - bundle install
  - yarn build
